### ISSUE TITLE
E2E: error retry, cancellation, and persistence across restarts

### ISSUE THREAD

**Issue by gregpriday** [canopyide/canopy#3867]
## Summary

The ErrorService supports retry with exponential backoff (base 500ms, cap 10s, jitter), AbortController-based cancellation, and persistence of critical errors to electron-store for crash recovery. None of these flows have e2e coverage.

## Problem Statement

The retry system involves coordination across main process (ErrorService retry loop), IPC bridge (ERROR_RETRY, ERROR_RETRY_CANCEL, ERROR_RETRY_PROGRESS channels), and renderer (retry button, progress UI, cancel button in ProblemsContent). A regression in any layer would silently break error recovery without automated detection.

The persistence path (critical errors buffered to electron-store, restored on next launch via `getPendingPersistedErrors()`) is similarly untested end-to-end.

## Context

**Retry infrastructure:**
- Retry config: [`electron/ipc/errorHandlers.ts#L28-L41`](https://github.com/canopyide/canopy/blob/9b742778/electron/ipc/errorHandlers.ts#L28-L41) — max attempts per action type, backoff calculation
- Retry handler: [`electron/ipc/errorHandlers.ts#L350-L387`](https://github.com/canopyide/canopy/blob/9b742778/electron/ipc/errorHandlers.ts#L350-L387) — loop with AbortController
- Retry UI: [`src/components/Diagnostics/ProblemsContent.tsx`](https://github.com/canopyide/canopy/blob/9b742778/src/components/Diagnostics/ProblemsContent.tsx) — retry button, progress indicator, cancel
- Preload: [`electron/preload.cts`](https://github.com/canopyide/canopy/blob/9b742778/electron/preload.cts) — errors.retry, errors.cancelRetry, errors.onRetryProgress

**Persistence:**
- Buffer: [`electron/ipc/errorHandlers.ts#L227-L246`](https://github.com/canopyide/canopy/blob/9b742778/electron/ipc/errorHandlers.ts#L227-L246) — pendingQueue + electron-store for critical errors
- Restore: [`electron/ipc/errorHandlers.ts#L298-L306`](https://github.com/canopyide/canopy/blob/9b742778/electron/ipc/errorHandlers.ts#L298-L306) — getPendingPersistedErrors with fromPreviousSession flag

**Existing restart test pattern:** [`e2e/core/core-persistence.spec.ts`](https://github.com/canopyide/canopy/blob/9b742778/e2e/core/core-persistence.spec.ts) — uses shared userDataDir across two app launches.

## Scope & Constraints

**Not in scope:** Testing the exact backoff timing values (unit test territory). E2e tests should verify the retry flow works, not that the delay is exactly 500ms * 2^attempt.

**Constraints:**
- Retry tests need fault injection that fails N times then succeeds — requires fault registry from #3854 to support a "fail count" mode
- Persistence tests need two app launches with the same userDataDir

## Acceptance Criteria

- [ ] Test verifies clicking retry on a transient error triggers retry progress UI
- [ ] Test verifies retry succeeds after a transient failure clears the error from the problems panel
- [ ] Test verifies cancel retry stops the retry loop and error remains in problems panel
- [ ] Test verifies critical errors (filesystem/config type) persist to electron-store and appear after app restart with `fromPreviousSession` indicator
- [ ] `npm run check` passes

## How to Test Locally

```bash
npx playwright test e2e/core/core-ipc-error-retry.spec.ts --headed
npx playwright test e2e/core/core-ipc-error-retry.spec.ts
```

## Edge Cases & Risks

- Retry backoff uses real timers in the main process — `page.clock.fastForward()` does NOT affect main process timers. Tests must either accept real delays or use short fault durations.
- AbortSignal cannot be serialized over IPC — Canopy correctly uses correlation IDs (error IDs), but the test must verify this indirection works.
- Persistence tests are inherently slower due to two full app launch/close cycles.

## Dependencies

Depends on #3854

---

## Verification Process

Every new E2E test must pass this workflow before merging:

**1. Local headed (debug):**
```bash
npm run build
npx playwright test e2e/core/<your-spec-file>.spec.ts --project=core --headed
```

**2. Local headless (CI-like):**
```bash
npx playwright test e2e/core/<your-spec-file>.spec.ts --project=core
```

**3. Push and trigger CI for your specific file:**
```bash
git push origin HEAD
gh workflow run e2e-core.yml --ref $(git branch --show-current) \
  -f platform=linux \
  -f test_file=e2e/core/<your-spec-file>.spec.ts
```

**4. Watch the CI run:**
```bash
gh run list --workflow=e2e-core.yml --limit=1
gh run watch          # streams live output
```

**5. On green**, update the PR description confirming CI passed. On red, download the trace artifact and debug:
```bash
gh run download <run-id> -n e2e-core-results-Linux-<sha>
npx playwright show-trace test-results/<trace-file>.zip
```
