### ISSUE TITLE
URLs in agent terminals not clickable after WebLinksAddon removal

### ISSUE THREAD

**Issue by gregpriday** [canopyide/canopy#3820]
## Summary

URLs printed in agent terminal output are not clickable. This regression was introduced when `@xterm/addon-web-links` was removed in #3659, which assumed the backend `UrlStyler` (OSC 8 hyperlink wrapping) fully replaced the addon's functionality. It did not.

## Current Behavior

- URLs in agent terminal output appear as plain text — they are not clickable and not visually styled as links
- The backend `UrlStyler` (`electron/services/pty/UrlStyler.ts`) attempts to wrap URLs with OSC 8 escape sequences before output reaches xterm.js
- This approach is fragile: `styleUrls()` has already failed for ANSI-colored output (fixed in `a11a6a8e`) and likely misses URLs in other edge cases (split across PTY chunks, embedded in complex escape sequences, etc.)
- The `linkHandler` option on the xterm.js Terminal (`src/services/terminal/TerminalInstanceService.ts:459-464`) only handles clicks on **already-formatted** OSC 8 sequences — it does not detect plain-text URLs

## Expected Behavior

- All `http://` and `https://` URLs in terminal output should be visually styled (underlined, colored) and clickable
- Clicking a URL should open it via the existing `TerminalLinkHandler` (external browser or embedded browser panel for localhost)
- This should work reliably regardless of surrounding ANSI escape sequences, output chunking, or whether the backend `UrlStyler` successfully wrapped the URL

## Root Cause Analysis

The `WebLinksAddon` and the backend `UrlStyler` serve **different, complementary roles**:

| Layer | Mechanism | What it catches |
|-------|-----------|-----------------|
| **Backend** (`UrlStyler`) | Regex on PTY output chunks → OSC 8 wrapping | URLs in clean text, before ANSI processing |
| **Frontend** (`WebLinksAddon`) | Regex on xterm.js buffer lines → `ILinkProvider` | Plain-text URLs visible in the terminal buffer |

The `WebLinksAddon` acts as a **client-side safety net** — it catches any URL that the backend missed (due to chunking, ANSI interference, or regex limitations). Removing it left the system with a single point of failure.

Per xterm.js 6.0 documentation: OSC 8 native support only handles pre-formatted hyperlink escape sequences. The `@xterm/addon-web-links` addon is still required for detecting and linking plain-text URLs via regex pattern matching on the terminal buffer.

**Evidence:**
- [`electron/services/pty/UrlStyler.ts`](https://github.com/canopyide/canopy/blob/develop/electron/services/pty/UrlStyler.ts#L60-L82) — backend URL wrapping with known fragility (skips text with existing OSC 8, susceptible to chunk-splitting)
- [`electron/services/pty/TerminalProcess.ts#L1304`](https://github.com/canopyide/canopy/blob/develop/electron/services/pty/TerminalProcess.ts#L1304) — where `styleUrls` is called in the PTY data pipeline
- [`src/services/terminal/TerminalAddonManager.ts`](https://github.com/canopyide/canopy/blob/develop/src/services/terminal/TerminalAddonManager.ts) — current addon setup, no web-links addon present
- [`src/services/terminal/TerminalInstanceService.ts#L459-L464`](https://github.com/canopyide/canopy/blob/develop/src/services/terminal/TerminalInstanceService.ts#L459-L464) — `linkHandler` configured for OSC 8 clicks only
- [`src/services/terminal/TerminalLinkHandler.ts`](https://github.com/canopyide/canopy/blob/develop/src/services/terminal/TerminalLinkHandler.ts) — existing link open logic (external browser + localhost → embedded browser)

**History:**
- #3659 / `697c7807` — Removed `@xterm/addon-web-links` as "redundant"
- `a11a6a8e` — Patched `UrlStyler` to stop skipping ANSI-colored text (symptom fix, not root cause)

## Scope & Constraints

**Not in scope:**
- Changing the `FileLinksAddon` (file path links) — this is a separate system using `ILinkProvider` and works independently
- Removing the backend `UrlStyler` — it still provides value for visual styling of URLs in headless/scrollback contexts

**Backwards compatibility:** The `TerminalLinkHandler` already has the correct click-handling logic. The fix should route through the same handler.

**Security:** Must not allow `javascript:` or other dangerous URI schemes. Only `http://` and `https://` URLs should be clickable.

## Acceptance Criteria

- [ ] `http://` and `https://` URLs in agent terminal output are visually identifiable and clickable
- [ ] Clicking a URL invokes the existing `TerminalLinkHandler` behavior (external open, or localhost → browser panel with modifier key)
- [ ] URLs surrounded by ANSI color codes (common in agent output like Claude, Gemini) are correctly detected and clickable
- [ ] No double-linking: URLs already wrapped with OSC 8 by the backend should not get a second link layer
- [ ] `npm run check` passes

## Edge Cases & Risks

- **Double-linking with UrlStyler:** If the backend successfully wraps a URL with OSC 8, adding a `WebLinksAddon` link on top could cause visual artifacts or double-click handlers. The two systems need to coexist without conflict.
- **Modifier key behavior:** The existing `linkHandler` uses Cmd/Ctrl+click for localhost URLs. The web-links addon click handler should preserve this behavior.
- **Performance:** The addon runs regex on visible buffer lines. With the DOM renderer and many terminals, ensure this doesn't add noticeable overhead (though it didn't before removal).
